networks:
  zabbix-net:
    driver: bridge

volumes:
  pgdata: {}
  snmptraps: {}
  zbx_modules: {}

services:

  timescaledb:
    image: timescale/timescaledb-postgis:latest-pg15
    container_name: tsdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zabbix
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zabbix-net
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.5-latest
    depends_on:
      - timescaledb
    environment:
      DB_SERVER_HOST: timescaledb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_ENABLE_SSL: "true"
      ZBX_TLSCA: /etc/zabbix/ssl/ca.pem
      ZBX_TLSCERT: /etc/zabbix/ssl/server.crt
      ZBX_TLSKEY: /etc/zabbix/ssl/server.key
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps
      - zbx_modules:/var/lib/zabbix/modules
      - ./ssl:/etc/zabbix/ssl:ro
    networks:
      - zabbix-net
    restart: unless-stopped

  web-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:6.5-latest
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: timescaledb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${TZ}
      ZBX_ENABLE_SSL: "true"
      ZBX_TLSCA: /etc/zabbix/ssl/ca.pem
      ZBX_TLSCERT: /etc/zabbix/ssl/web.crt
      ZBX_TLSKEY: /etc/zabbix/ssl/web.key
      ZBX_SESSION_SSO: "ldap"            # o "saml"
    volumes:
      - ./ssl:/etc/zabbix/ssl:ro
    networks:
      - zabbix-net
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zabbix.rule=Host(`${ZBX_FQDN}`)"
      - "traefik.http.routers.zabbix.entrypoints=websecure"
      - "traefik.http.routers.zabbix.tls=true"

  zabbix-agent:
    image: zabbix/zabbix-agent:6.5-latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_TLSCONNECT: psk
      ZBX_TLSPSK_FILE: /etc/zabbix/psk/agent.psk
    volumes:
      - ./psk:/etc/zabbix/psk:ro
    networks:
      - zabbix-net
    restart: unless-stopped
